export const theme = {
  media: {
    small: '(max-width: 414px)',
    medium: '(max-width: 390px)',
    large: '(max-width: 414px)',
    notebookHeight: '(max-height: 768px)',
  },
  colors: {
    primary: '#7f5af0',
    secondary: '#80F88D',
    inputText: '#',
    icons: '#',
    text: '#',
    title: '#',
    background: '#16161a',
    white: '#ffffff',
    success: '#4BB543',
    error: '#E51247',
  },
  space: {
    1: '',
    2: '',
    3: '',
  },
  fontSizes: {
    1: '1.6rem',
    2: '2rem',
    3: '3.2rem',
    4: '3.6rem',
    5: '4rem',
  },
  fonts: {
    Roboto: 'Roboto',
  },
  fontWeights: {},
  lineHeights: {},
  letterSpacings: {},
  sizes: {},
  borderWidths: {},
  borderStyles: {},
  borderRadius: {
    1: '5px',
    2: '10px',
    3: '15px',
  },
  shadows: {
    button: '2px 2px 5px rgba(0, 0, 0, 0.25)',
  },
  transitions: {},
};
